config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :tasks

 
  get "signup" ,to: "users#new"
  post "users", to: "users#create"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  
  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"

 root to: "tasks#index"
 

 end
 
 
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks
    before_save { self.email.downcase! }
    has_secure_password
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   
    email = params[:session][:email]
    password = params[:session][:password]
   
    if login(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to "/"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to login_url
  end
  
  private
  
  def login(email, password)

    @user = User.find_by(email: email)
    #authenticateメソッド（引数はpassword）は、@userに代入されているレコードのパスワードが正しいかを確認する
    if @user && @user.authenticate(password)
      #下記一文により、ブラウザにcookieとして、サーバーにsessionとして、ログイン状態が維持されることになります
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :require_user_logged_in
    before_action :correct_user, only: [:destroy, :edit, :show, :update]
    
    def index
        @tasks = current_user.tasks
    end
    
    def show
        # @task = Task.find(params[:id])
    end
    
    def new 
        @task = current_user.tasks.build
    end
    
    def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'タスクを追加しました。'
      redirect_to root_url
    else
      @tasks = Task.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'タスクの追加に失敗しました。'
      render :new
    end
    end
    
    def edit
        # @task = Task.find(params[:id])
    end
    
    def update
        @task = current_user.tasks.find(params[:id])
        
        if @task.update(task_params)
            flash[:success] = "タスクが編集されました"
            redirect_to @task
        else
            flash.now[:danger] = "タスクの編集に失敗しました"
            render :edit 
        end
    end
    
    
      def destroy
    # @task = Task.find(params[:id])
    @task.destroy

    flash.now[:success] = 'タスク は正常に削除されました'
    redirect_to tasks_url
      end
     
    private
    
    def task_params
        params.require(:task).permit(:content, :status)
    end
    
    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        unless @task
            redirect_to tasks_url
        end
    end
     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザ登録が完了しました"
      redirect_to login_url
    else
      flash.now[:danger] = "ユーザ登録に失敗しました"
      render :new
    end
  end
    
  private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
<div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel = "stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
  </head>

  <body>
    <div class="container">
    <%= render "layouts/flash_messages" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model:@task, local: true) do |f| %>
<%= render "layouts/error_messages", model: @task %>
 <%= f.label :content, "タスク" %>
 <%= f.text_field :content %>
 <%= f.label :status, "ステータス" %>
 <%= f.text_field :status %>
 
 <%= f.submit message %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

<%= render "form.html.erb", message: "編集完了" %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>

<h1>タスク一覧</h1>
<p><%= link_to "タスクの追加", new_task_path %></p>
<ul>
    <% @tasks.each do |task| %>
    <li><%= task.status %>：<%= task.content %>:<%= link_to task.id, task %> </li>
    <% end %>
</ul>
<p><%= link_to "logout", logout_path %></p>

<% else %>

<div class="row">
    <div class="col-sm-6">
        <h2 class="text-center">Welcome to Tasklist!!</h2>
        <p><%= link_to "signup", signup_path %></p>
    </div>
    
    <div class="col-sm-6">
        <h2>Welcome back Tasklist!!</h2>
        <p><%= link_to "login", login_path %></p>
        
    </div>
</div>

<% end %>

app/views/tasks/new.html.erb
<h1>タスクの追加</h1>

 <%= render "form.html.erb", message: "追加する" %>
 
 

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %></h1>
<p><%= @task.content %></p>
<p><%= @task.status %></p>
<p><%= link_to "一覧に戻る", tasks_path %></p>
<p><%= link_to "このタスクを編集する", edit_task_path %></p>
<p><%= link_to "このタスクを削除する", @task, method: :delete, data: { confirm: "ほんとに削除するんけ？" } %></p>

app/views/users/new.html.erb
<h1>新規ユーザ登録</h1>
<%= form_with(model: @user, local: true) do |f| %>

<% if f.object.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 
 <%= f.label :name, "Name" %>
 <%= f.text_field :name %>

 <%= f.label :email, "Email" %>
 <%= f.email_field :email %>
 
 <%= f.label :password, "Password" %>
 <%= f.password_field :password %>
 
 <%= f.label :password_confirmation, "Password_confirmation" %>
 <%= f.password_field :password_confirmation %>
 
 <%= f.submit "Sign up" %>
 
 <%= link_to "Log in", login_path %>
<% end %>